# Generated by Django 2.1.7 on 2019-03-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wjlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fullName',
            field=models.CharField(default='Full name', max_length=30),
            preserve_default=False,
        ),
    ]
