# Generated by Django 2.1.7 on 2019-04-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wjlibrary', '0003_auto_20190330_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default='SAMPLE', max_length=30),
            preserve_default=False,
        ),
    ]
