# Generated by Django 2.1.7 on 2019-04-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wjlibrary', '0004_author_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='world',
            name='authors',
        ),
        migrations.AddField(
            model_name='world',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wjlibrary.Author'),
        ),
    ]
