# Generated by Django 2.1.7 on 2019-04-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wjlibrary', '0006_auto_20190412_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='purpose',
            field=models.TextField(default='The author has not yet described their purpose in creating this world.'),
        ),
    ]
